config/routes.rb
Rails.application.routes.draw do
  root 'personals#index'
  resources :rewardtables
  resources :idtables
  resources :personals

  get 'join', to: 'personals#join', as: 'joinp'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idtable.rb
class Idtable < ApplicationRecord
    has_many :personals
end

app/models/personal.rb
class Personal < ApplicationRecord
    #belongs_to :idtable
    #belongs_to :rewardtable
end

app/models/rewardtable.rb
class Rewardtable < ApplicationRecord
    #has_many :personals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/idtables_controller.rb
class IdtablesController < ApplicationController
  before_action :set_idtable, only: [:show, :edit, :update, :destroy]

  # GET /idtables
  # GET /idtables.json
  def index
    @idtables = Idtable.all
  end

  # GET /idtables/1
  # GET /idtables/1.json
  def show
  end

  # GET /idtables/new
  def new
    @idtable = Idtable.new
  end

  # GET /idtables/1/edit
  def edit
  end

  # POST /idtables
  # POST /idtables.json
  def create
    @idtable = Idtable.new(idtable_params)

    respond_to do |format|
      if @idtable.save
        format.html { redirect_to @idtable, notice: 'Idtable was successfully created.' }
        format.json { render :show, status: :created, location: @idtable }
      else
        format.html { render :new }
        format.json { render json: @idtable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idtables/1
  # PATCH/PUT /idtables/1.json
  def update
    respond_to do |format|
      if @idtable.update(idtable_params)
        format.html { redirect_to @idtable, notice: 'Idtable was successfully updated.' }
        format.json { render :show, status: :ok, location: @idtable }
      else
        format.html { render :edit }
        format.json { render json: @idtable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idtables/1
  # DELETE /idtables/1.json
  def destroy
    @idtable.destroy
    respond_to do |format|
      format.html { redirect_to idtables_url, notice: 'Idtable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idtable
      @idtable = Idtable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idtable_params
      params.require(:idtable).permit(:idtype, :minbal)
    end
end

app/controllers/personals_controller.rb
class PersonalsController < ApplicationController
  before_action :set_personal, only: [:show, :edit, :update, :destroy]

  # GET /personals
  # GET /personals.json
  def index
    @personals = Personal.all
  end

  # GET /personals/1
  # GET /personals/1.json
  def show
  end

  # GET /personals/new
  def new
    @personal = Personal.new
  end

  # GET /personals/1/edit
  def edit
  end

  # GET /personals/1/join ?
  def join
    @join = Personal.select("personals.*,idtables.*,rewardtables.*").joins("INNER JOIN idtables ON idtables.idtype = personals.idtype INNER JOIN rewardtables ON rewardtables.rewardtype = personals.rewardtype")
  end

  # POST /personals
  # POST /personals.json
  def create
    @personal = Personal.new(personal_params)

    respond_to do |format|
      if @personal.save
        format.html { redirect_to @personal, notice: 'Personal was successfully created.' }
        format.json { render :show, status: :created, location: @personal }
      else
        format.html { render :new }
        format.json { render json: @personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personals/1
  # PATCH/PUT /personals/1.json
  def update
    respond_to do |format|
      if @personal.update(personal_params)
        format.html { redirect_to @personal, notice: 'Personal was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal }
      else
        format.html { render :edit }
        format.json { render json: @personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personals/1
  # DELETE /personals/1.json
  def destroy
    @personal.destroy
    respond_to do |format|
      format.html { redirect_to personals_url, notice: 'Personal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal
      @personal = Personal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_params
      params.require(:personal).permit(:email, :tel, :mobile, :idtype, :rewardtype)
    end
end

app/controllers/rewardtables_controller.rb
class RewardtablesController < ApplicationController
  before_action :set_rewardtable, only: [:show, :edit, :update, :destroy]

  # GET /rewardtables
  # GET /rewardtables.json
  def index
    @rewardtables = Rewardtable.all
  end

  # GET /rewardtables/1
  # GET /rewardtables/1.json
  def show
  end

  # GET /rewardtables/new
  def new
    @rewardtable = Rewardtable.new
  end

  # GET /rewardtables/1/edit
  def edit
  end

  # POST /rewardtables
  # POST /rewardtables.json
  def create
    @rewardtable = Rewardtable.new(rewardtable_params)

    respond_to do |format|
      if @rewardtable.save
        format.html { redirect_to @rewardtable, notice: 'Rewardtable was successfully created.' }
        format.json { render :show, status: :created, location: @rewardtable }
      else
        format.html { render :new }
        format.json { render json: @rewardtable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rewardtables/1
  # PATCH/PUT /rewardtables/1.json
  def update
    respond_to do |format|
      if @rewardtable.update(rewardtable_params)
        format.html { redirect_to @rewardtable, notice: 'Rewardtable was successfully updated.' }
        format.json { render :show, status: :ok, location: @rewardtable }
      else
        format.html { render :edit }
        format.json { render json: @rewardtable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewardtables/1
  # DELETE /rewardtables/1.json
  def destroy
    @rewardtable.destroy
    respond_to do |format|
      format.html { redirect_to rewardtables_url, notice: 'Rewardtable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rewardtable
      @rewardtable = Rewardtable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rewardtable_params
      params.require(:rewardtable).permit(:rewardtype, :pts)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/idtables_helper.rb
module IdtablesHelper
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/helpers/rewardtables_helper.rb
module RewardtablesHelper
end

app/views/idtables/edit.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="index.css">
</head>

<body style = "margin:25px; padding:0">
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top rounded-lg" 
    style="background-color: #0072CE !important;
    border-radius: 0rem !important;
    border-bottom-left-radius: 1.5rem !important;
    border-bottom-right-radius: 1.5rem !important;
    ">

    <a href="https://www.bdo.com.ph/personal"><%=image_tag("logo.svg",style: "height: 30px;")%></a>
    <a class="navbar-brand" href="#" style ="color: white !important;">
        Editing Record
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
              <div class="nav-link" style = "background-color:#efefef; border-color:transparent; border-radius: 0.5rem;"> <%= link_to 'Back', personals_path, style: "color:#1e4f8e"%></div>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style ="color:white;">
            Others
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" style ="background-color:#0072CE; ">
            <div class="dropdown-item"><%= link_to 'ID Types', idtables_path, style: "color:white"%></div>
            <div class="dropdown-item"><%= link_to 'Rewards', rewardtables_path, style: "color:white" %></div>
            <div class="dropdown-divider"></div>
            <div class="dropdown-item"><%= link_to 'All Records', joinp_path(@join), style: "color:white" %></div>
          </div>
        </li>
      </ul>
    </div>
  </nav> 

  <br><br>
    <%= render 'form', idtable: @idtable %>

</body>

app/views/idtables/index.html.erb
<body style = "margin: 15px; padding:0">
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top rounded-lg" 
  style="background-color: #0072CE !important;
  border-radius: 0rem !important;
  border-bottom-left-radius: 1.5rem !important;
  border-bottom-right-radius: 1.5rem !important;
  ">
    <a href="https://www.bdo.com.ph/personal"><%=image_tag("logo.svg",style: "height: 30px;")%></a>
    <a class="navbar-brand" href="#" style ="color: white !important;">
        ID Types
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <div class="nav-link" style = "background-color:#efefef; border-color:transparent; border-radius: 0.5rem;"> <%= link_to 'Back', personals_path, style: "color:#1e4f8e"%></div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style ="color:white;">
            Others
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" style ="background-color:#0072CE; ">
              <div class="dropdown-item"><%= link_to 'Rewards', rewardtables_path, style: "color:white" %></div>
              <div class="dropdown-divider"></div>
              <div class="dropdown-item"><%= link_to 'All Records', joinp_path(@join), style: "color:white" %></div>
          </div>
        </li>
      </ul>
    </div>
  </nav> 

<h1>Idtables</h1>
<div class="table-responsive">
  <table class = "table">
      <thead>
        <tr>
          <th>ID Type</th>
          <th>Minimum Balance</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @idtables.each do |idtable| %>
          <tr>
            <td><%= idtable.idtype %></td>
            <td><%= idtable.minbal %></td>
            <td><%= link_to 'Show', idtable, style: "color:#1e4f8e" %></td>
            <td><%= link_to 'Destroy', idtable, method: :delete, data: { confirm: 'Are you sure?' }, style: "color:#1e4f8e" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
</body>

app/views/idtables/new.html.erb
<h1>New Idtable</h1>

<%= render 'form', idtable: @idtable %>

<%= link_to 'Back', idtables_path %>

app/views/idtables/show.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<p id="notice"><%= notice %></p>

<body style = "margin:25px; padding:0">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top rounded-lg" 
    style="background-color: #0072CE !important;
    border-radius: 0rem !important;
    border-bottom-left-radius: 1.5rem !important;
    border-bottom-right-radius: 1.5rem !important;
    ">
      <a href="https://www.bdo.com.ph/personal"><%=image_tag("logo.svg",style: "height: 30px;")%></a>
      <a class="navbar-brand" href="#" style ="color: white !important;">
          ID Types
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
              <div class="nav-link" style = "background-color:#efefef; border-color:transparent; border-radius: 0.5rem;"> <%= link_to 'Back', personals_path, style: "color:#1e4f8e"%></div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style ="color:white;">
              Others
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown" style ="background-color:#0072CE; ">
              <div class="dropdown-item"><%= link_to 'ID Types', idtables_path, style: "color:white"%></div>
              <div class="dropdown-item"><%= link_to 'Rewards', rewardtables_path, style: "color:white" %></div>
            </div>
          </li>
        </ul>
      </div>
    </nav> 

    <br><br>
    <p>
      <strong>ID Type:</strong>
      <%= @idtable.idtype %>
    </p>

    <p>
      <strong>Minimum Balance:</strong>
      <%= @idtable.minbal %>
    </p>

  </div>

</body>

app/views/personals/edit.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="index.css">
</head>

<body style = "margin:25px; padding:0">
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top rounded-lg" 
    style="background-color: #0072CE !important;
    border-radius: 0rem !important;
    border-bottom-left-radius: 1.5rem !important;
    border-bottom-right-radius: 1.5rem !important;
    ">

    <a href="https://www.bdo.com.ph/personal"><%=image_tag("logo.svg",style: "height: 30px;")%></a>
    <a class="navbar-brand" href="#" style ="color: white !important;">
        Editing Record
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
              <div class="nav-link" style = "background-color:#efefef; border-color:transparent; border-radius: 0.5rem;"> <%= link_to 'Back', personals_path, style: "color:#1e4f8e"%></div>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style ="color:white;">
            Others
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" style ="background-color:#0072CE; ">
            <div class="dropdown-item"><%= link_to 'ID Types', idtables_path, style: "color:white"%></div>
            <div class="dropdown-item"><%= link_to 'Rewards', rewardtables_path, style: "color:white" %></div>
            <div class="dropdown-divider"></div>
            <div class="dropdown-item"><%= link_to 'All Records', joinp_path(@join), style: "color:white" %></div>
          </div>
        </li>
      </ul>
    </div>
  </nav> 

  <br><br>

  <%= render 'form', personal: @personal %>
  <br>
</body>

app/views/personals/index.html.erb
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="index.css">
  </head>
  
<body style="margin:30px;padding:0">
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top rounded-lg" 
  style="background-color: #0072CE !important;
    border-radius: 0rem !important;
    border-bottom-left-radius: 1.5rem !important;
    border-bottom-right-radius: 1.5rem !important;
    ">

      <a href="https://www.bdo.com.ph/personal"><%=image_tag("logo.svg",style: "height: 30px;")%></a>
      <a class="navbar-brand" href="#" style ="color: white !important;">
          Personal
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
              <div class="nav-link" style = "background-color:#efefef; border-color:transparent; border-radius: 0.5rem;"> <%= link_to 'New Record', new_personal_path, style: "color:#1e4f8e"%></div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style ="color:white;">
              Others
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown" style ="background-color:#0072CE; ">
              <div class="dropdown-item"><%= link_to 'ID Types', idtables_path, style: "color:white"%></div>
              <div class="dropdown-item"><%= link_to 'Rewards', rewardtables_path, style: "color:white" %></div>
              <div class="dropdown-divider"></div>
              <div class="dropdown-item"><%= link_to 'All Records', joinp_path(@join), style: "color:white" %></div>
            </div>
          </li>
        </ul>
      </div>
    </nav> 
  <br><br>
  <p id="notice"><%= notice %></p>
    <div class = "card-columns">
      <% @personals.each do |personal| %>
        <div class = "card border-light">
          <div class = "card-header">
            <h4 class ="col-md-6 text-left my-auto" style="white-space:nowrap"><%= personal.email %></h4>
          
            <div class = "btn-group col-md-6 text-right my-auto ">
                <button class="btn btn-primary" style = "background-color:#f7af19; border-color:transparent;"><%= link_to 'Show', personal, style: "color:white"%></button>
                <button class="btn btn-primary" style = "background-color:#f7af19; border-color:transparent;"><%= link_to 'Edit', edit_personal_path(personal), style: "color:white" %></button>
                <button class="btn btn-danger"><%= link_to 'Delete', personal, method: :delete, data: { confirm: 'Are you sure?' },  style: "color:white"%></button>
            </div>
          </div>

          <ul class="list-group list-group-flush">
            <li class = "list-group-item">
              <h6 class = "card-subtitle">Tel. Number</h6>
              <%= personal.tel %>
            </li>
            <li class = "list-group-item">
              <h6 class = "card-subtitle">Mobile Number</h6>
              <%= personal.mobile %>
            </li>
            <li class = "list-group-item">
              <h6 class = "card-subtitle">ID Type</h6>
              <%= personal.idtype %>
            </li>
            <li class = "list-group-item">
              <h6 class = "card-subtitle">Reward Type</h6>
              <%= personal.rewardtype %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
</body>

app/views/personals/join.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="join.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body style = "margin:15px; padding:0">
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top rounded-lg" 
  style="background-color: #0072CE !important;
  border-radius: 0rem !important;
  border-bottom-left-radius: 1.5rem !important;
  border-bottom-right-radius: 1.5rem !important;
  ">
    <a href="https://www.bdo.com.ph/personal"><%=image_tag("logo.svg",style: "height: 30px;")%></a>
    <a class="navbar-brand" href="#" style ="color: white !important;">
        Personal
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <div class="nav-link" style = "background-color:#efefef; border-color:transparent; border-radius: 0.5rem;"> <%= link_to 'Back', personals_path, style: "color:#1e4f8e"%></div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style ="color:white;">
            Others
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" style ="background-color:#0072CE; ">
            <div class="dropdown-item"><%= link_to 'ID Types', idtables_path, style: "color:white"%></div>
            <div class="dropdown-item"><%= link_to 'Rewards', rewardtables_path, style: "color:white" %></div>
          </div>
        </li>
      </ul>
    </div>
  </nav> 
  
    <br>
    <br>
    <br>
    
  <div class="table-responsive">
    <table class ="table">
        <thead>
          <tr>
            <th>Email Address</th>
            <th>Telephone Number</th>
            <th>Mobile Number</th>
            <th>ID Type</th>
            <th>Mininum Balance</th>
            <th>Reward Type</th>
            <th>Points</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @join.each do |join| %>
            <tr>
              <td><%= join.email %></td>
              <td><%= join.tel %></td>
              <td><%= join.mobile %></td>
              <td><%= join.idtype %></td>
              <td>&#x20B1 <%= join.minbal %></td>
              <td><%= join.rewardtype %></td>
              <td><%= join.pts %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</body>

app/views/personals/new.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="index.css">
</head>

<body style = "margin:25px; padding:0">
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top rounded-lg" 
style="background-color: #0072CE !important;
  border-radius: 0rem !important;
  border-bottom-left-radius: 1.5rem !important;
  border-bottom-right-radius: 1.5rem !important;
  ">

    <a href="https://www.bdo.com.ph/personal"><%=image_tag("logo.svg",style: "height: 30px;")%></a>
    <a class="navbar-brand" href="#" style ="color: white !important;">
        New Record
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style ="color:white;">
            Others
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" style ="background-color:#0072CE; ">
            <div class="dropdown-item"><%= link_to 'ID Types', idtables_path, style: "color:white"%></div>
            <div class="dropdown-item"><%= link_to 'Rewards', rewardtables_path, style: "color:white" %></div>
            <div class="dropdown-divider"></div>
            <div class="dropdown-item"><%= link_to 'All Records', joinp_path(@join), style: "color:white" %></div>
          </div>
        </li>
      </ul>
    </div>
  </nav> 

  <br><br>

<%= render 'form', personal: @personal %>

</body>

app/views/personals/show.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<p id="notice"><%= notice %></p>

<body style = "margin:25px; padding:0">
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top rounded-lg" 
  style="background-color: #0072CE !important;
  border-radius: 0rem !important;
  border-bottom-left-radius: 1.5rem !important;
  border-bottom-right-radius: 1.5rem !important;
  ">
    <a href="https://www.bdo.com.ph/personal"><%=image_tag("logo.svg",style: "height: 30px;")%></a>
    <a class="navbar-brand" href="#" style ="color: white !important;">
        Personal
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <div class="nav-link" style = "background-color:#efefef; border-color:transparent; border-radius: 0.5rem;"> <%= link_to 'Back', personals_path, style: "color:#1e4f8e"%></div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style ="color:white;">
            Others
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" style ="background-color:#0072CE; ">
            <div class="dropdown-item"><%= link_to 'ID Types', idtables_path, style: "color:white"%></div>
            <div class="dropdown-item"><%= link_to 'Rewards', rewardtables_path, style: "color:white" %></div>
          </div>
        </li>
      </ul>
    </div>
  </nav> 

  <br><br>

  <p>
    <strong>Email Address:</strong>
    <%= @personal.email %>
  </p>

  <p>
    <strong>Telephone Number:</strong>
    <%= @personal.tel %>
  </p>

  <p>
    <strong>Mobile Number:</strong>
    <%= @personal.mobile %>
  </p>

  <p>
    <strong>ID Type:</strong>
    <%= @personal.idtype %>
  </p>

  <p>
    <strong>Reward Type:</strong>
    <%= @personal.rewardtype %>
  </p>

  <%= link_to 'Edit', edit_personal_path(@personal), style: "color:#1e4f8e"%>
</body>

app/views/rewardtables/edit.html.erb
<h1>Editing Rewardtable</h1>

<%= render 'form', rewardtable: @rewardtable %>

<%= link_to 'Show', @rewardtable %> |
<%= link_to 'Back', rewardtables_path %>

app/views/rewardtables/new.html.erb
<h1>New Rewardtable</h1>

<%= render 'form', rewardtable: @rewardtable %>

<%= link_to 'Back', rewardtables_path %>